name: Update heatmap
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 5 * * *' # run every day at 5 am
jobs:
  build:
    runs-on: macos-11
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "${{ secrets.GIT_USEREMAIL }}"
        git config --global user.name "${{ secrets.GIT_USERNAME }}"
        git config --global user.token "${{ secrets.GIT_CREDENTIALS }}"
        git add -A
        git commit -m "Updated sleep data" || exit 0
        git push